// Core.React/corereact/src/App.tsx
import * as React from 'react';
import { CalculoAppService } from './coreapp/App.Core/CalculoAppService'
import { Operacao } from './coreapp/App.Core/Domain/EnumOperacao'
import './App.css';

let appService = new CalculoAppService();

interface Props {

}

interface Calculo {
  valorA?: number;
  valorB?: number;
  resultado?: Number;
  operacao: Operacao;
  error?: string;
  itens: Array<any>;
}

class App extends React.Component<Props, Calculo> {


  constructor() {
    super();

    this.state = {
      itens: appService.getOperators(),
      operacao: appService.getDefaultOperator()
    };

    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
  }

  handleChange(e: any) {
    this.setState({ [e.target.name]: e.target.value });
  }

  handleSubmit(event: any) {
    try {
      let resultado = appService.calcular(Number(this.state.valorA), Number(this.state.valorB), Number(this.state.operacao));
      this.setState({ resultado: resultado, error: undefined });
    } catch (ex) {
      this.setState({ resultado: undefined, error: ex.toString() });
    }
  }


  render() {

    let listItems = this.state.itens.map((item) => {
      return (
        <span>
          <input type="radio" id={item.value} value={item.value} name="operacao" onChange={this.handleChange} checked={this.state.operacao == item.value ? true : false} ></input>
          <label htmlFor={item.value}>&nbsp;{item.text}</label>
          <br />
        </span>
      );
    });


    let errorBox = this.state.error != undefined ? (<div className="alert alert-danger" role="alert">
                    {this.state.error}
                   </div> ) : undefined;


    let resultBox = this.state.resultado != undefined ? (<div className="alert alert-success" role="alert">
                O resultado é: {this.state.resultado}
              </div> ) : undefined;


    return (
      <div className="container">
        <h2>Criado com React do Facebruiks</h2>
        <div className="row">
          <div className="form-group">
            <input className="form-control" placeholder="Valor 1" value={this.state.valorA} name="valorA" onChange={this.handleChange}></input>
          </div>
          <div className="form-group">
            <input className="form-control" placeholder="Valor 2" value={this.state.valorB} name="valorB" onChange={this.handleChange} ></input>
          </div>
          {listItems}
          <div className="form-group">
            <button className="btn btn-primary pull-right" onClick={this.handleSubmit} >Calcular</button>
          </div>
          <hr />
          { errorBox }
          { resultBox }
        </div>
      </div>
    );
  }
}

export default App;

// Core.Angular4/src/app/app.component.ts
import { Component } from '@angular/core';
import { CalculoAppService } from '../../../Core/src/App.Core/CalculoAppService'
import { Operacao } from '../../../Core/src/App.Core/Domain/EnumOperacao'

let appService = new CalculoAppService();

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  valorA?: number = undefined;
  valorB?: number = undefined;
  operacao: number = undefined;  
  error?: string = undefined;
  resultado?: number = undefined;
  itens: Array<any> = undefined;

  constructor() {
    this.itens = appService.getOperators();
    this.operacao = appService.getDefaultOperator();
  }

  calcular() {
    try {
      this.resultado = appService.calcular(Number(this.valorA), Number(this.valorB), this.operacao);
      this.error = undefined;
    } catch (ex) {
      this.resultado = undefined;
      this.error = ex.toString();
    }
  }

}

<!--The content below is only a placeholder and can be replaced.-->
<div class="container">
  <h2>Criado com Angular4 do henn</h2>
  <div class="row">
    <div class="form-group">
      <input class="form-control" placeholder="Valor 1" [(ngModel)]="valorA" >
    </div>
    <div class="form-group">
      <input class="form-control" placeholder="Valor 2" [(ngModel)]="valorB">
    </div>
    <span *ngFor="let item of itens">
      <input type="radio" [id]="item.value" [value]="item.value" [(ngModel)]="operacao">
      <label [for]="item.value">{{item.text}}</label>
      <br>
    </span>
    <div class="form-group">
      <button class="btn btn-primary pull-right" (click)="calcular()">Calcular</button>
    </div>
    <hr>
    <div class="alert alert-danger" role="alert" [hidden]="!error">
      {{error}}
    </div>
    <div class="alert alert-success" role="alert" [hidden]="resultado == undefined">
      O resultado é: {{resultado}}
    </div>
  </div>
</div>
